export const LIST_PRODUCT = "LIST_PRODUCT";
export const DETAIL_PRODUCT = "DETAIL_PRODUCT";
export const ADD_PRODUCT = "ADD_PRODUCT";
export const EDIT_PRODUCT = "EDIT_PRODUCT";
export const DELETE_PRODUCT = "DELETE_PRODUCT";
export const GET_PARAMS = "GET_PARAMS";
export const PRODUCT_ID = "PRODUCT_ID";
export const START_FETCHING = "START_FETCHING";
